// <auto-generated />
using System;
using Backend.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912152431_AdicionaPerfisDeFormandos")]
    partial class AdicionaPerfisDeFormandos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Business.Arquivos.Models.Arquivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("categoria");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("chave");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EnviadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("enviado_por_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<long>("Tamanho")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho");

                    b.HasKey("Id")
                        .HasName("pk_arquivos");

                    b.HasIndex("Chave")
                        .IsUnique()
                        .HasDatabaseName("ix_arquivos_chave");

                    b.HasIndex("EnviadoPorId", "Categoria", "CriadoEm")
                        .HasDatabaseName("ix_arquivos_enviado_por_id_categoria_criado_em");

                    b.ToTable("arquivos", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Assinaturas.Models.Assinatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime?>("CanceladaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelada_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("FormaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("formatura_id");

                    b.Property<string>("IdExterno")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id_externo");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("UltimoAvisoDeVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("ultimo_aviso_de_vencimento");

                    b.Property<DateTime?>("VigenteAte")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_ate");

                    b.HasKey("Id")
                        .HasName("pk_assinaturas");

                    b.HasIndex("FormaturaId")
                        .HasDatabaseName("ix_assinaturas_formatura_id");

                    b.HasIndex("PlanoId")
                        .HasDatabaseName("ix_assinaturas_plano_id");

                    b.HasIndex("Status", "VigenteAte")
                        .HasDatabaseName("ix_assinaturas_status_vigente_ate");

                    b.HasIndex(new[] { "FormaturaId" }, "ix_assinaturas_pendente_por_formatura")
                        .IsUnique()
                        .HasDatabaseName("ix_assinaturas_pendente_por_formatura")
                        .HasFilter("status = 'Pendente'");

                    b.ToTable("assinaturas", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Assinaturas.Models.EventoDeCobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssinaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("assinatura_id");

                    b.Property<Guid?>("FormaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("formatura_id");

                    b.Property<string>("IdExterno")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id_externo");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<DateTime>("RecebidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebido_em");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_eventos_de_cobranca");

                    b.HasIndex("AssinaturaId")
                        .HasDatabaseName("ix_eventos_de_cobranca_assinatura_id");

                    b.HasIndex("IdExterno")
                        .IsUnique()
                        .HasDatabaseName("ix_eventos_de_cobranca_id_externo");

                    b.ToTable("eventos_de_cobranca", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Assinaturas.Models.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Ciclo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ciclo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("LimiteDeFormandos")
                        .HasColumnType("integer")
                        .HasColumnName("limite_de_formandos");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<long>("PrecoEmCentavos")
                        .HasColumnType("bigint")
                        .HasColumnName("preco_em_centavos");

                    b.Property<bool>("Recomendado")
                        .HasColumnType("boolean")
                        .HasColumnName("recomendado");

                    b.HasKey("Id")
                        .HasName("pk_planos");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_planos_codigo");

                    b.ToTable("planos", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Auth.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("CriadoPorIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("criado_por_ip");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid?>("FormaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("formatura_id");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<string>("SubstituidoPorHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("substituido_por_hash");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UsuarioId", "RevogadoEm")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id_revogado_em");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Convites.Models.AceiteDeConvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AceitoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aceito_em");

                    b.Property<Guid>("ConviteId")
                        .HasColumnType("uuid")
                        .HasColumnName("convite_id");

                    b.Property<string>("EnderecoIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("endereco_ip");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_aceites_de_convite");

                    b.HasIndex("ConviteId")
                        .HasDatabaseName("ix_aceites_de_convite_convite_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_aceites_de_convite_usuario_id");

                    b.ToTable("aceites_de_convite", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Convites.Models.Convite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("FormaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("formatura_id");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("papel");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UsosFeitos")
                        .HasColumnType("integer")
                        .HasColumnName("usos_feitos");

                    b.Property<int?>("UsosMaximos")
                        .HasColumnType("integer")
                        .HasColumnName("usos_maximos");

                    b.HasKey("Id")
                        .HasName("pk_convites");

                    b.HasIndex("CriadoPorUsuarioId")
                        .HasDatabaseName("ix_convites_criado_por_usuario_id");

                    b.HasIndex("FormaturaId")
                        .HasDatabaseName("ix_convites_formatura_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_convites_token_hash");

                    b.ToTable("convites", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Emails.Models.EmailNaFila", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("assunto");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CorpoHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo_html");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<string>("Para")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("para");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer")
                        .HasColumnName("prioridade");

                    b.Property<DateTime>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa_em");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ultimo_erro");

                    b.HasKey("Id")
                        .HasName("pk_emails_fila");

                    b.HasIndex("Status", "ProximaTentativaEm", "Prioridade")
                        .HasDatabaseName("ix_emails_fila_status_proxima_tentativa_em_prioridade")
                        .HasFilter("status = 0");

                    b.ToTable("emails_fila", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Eventos.Models.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Dados")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<DateTime>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<string>("Rota")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("rota");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_eventos");

                    b.HasIndex("OcorridoEm", "Nome")
                        .HasDatabaseName("ix_eventos_ocorrido_em_nome");

                    b.HasIndex("UsuarioId", "OcorridoEm")
                        .HasDatabaseName("ix_eventos_usuario_id_ocorrido_em");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Formandos.Models.CorrecaoDePerfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_usuario_id");

                    b.Property<DateTime>("CorrigidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("corrigido_em");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Secoes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("secoes");

                    b.HasKey("Id")
                        .HasName("pk_correcoes_de_perfil");

                    b.HasIndex("AutorUsuarioId")
                        .HasDatabaseName("ix_correcoes_de_perfil_autor_usuario_id");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_correcoes_de_perfil_perfil_id");

                    b.ToTable("correcoes_de_perfil", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Formandos.Models.PerfilDoFormando", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("Completude")
                        .HasColumnType("integer")
                        .HasColumnName("completude");

                    b.Property<string>("Cpf")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataDeNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_de_nascimento");

                    b.Property<bool>("EssencialPreenchido")
                        .HasColumnType("boolean")
                        .HasColumnName("essencial_preenchido");

                    b.Property<Guid>("FormaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("formatura_id");

                    b.Property<Guid?>("FotoArquivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("foto_arquivo_id");

                    b.Property<string>("Matricula")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("matricula");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("NomeNoDiploma")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_no_diploma");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<string>("Telefone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("telefone");

                    b.Property<Guid>("VinculoId")
                        .HasColumnType("uuid")
                        .HasColumnName("vinculo_id");

                    b.HasKey("Id")
                        .HasName("pk_perfis_de_formandos");

                    b.HasIndex("FormaturaId")
                        .HasDatabaseName("ix_perfis_de_formandos_formatura_id");

                    b.HasIndex("FotoArquivoId")
                        .HasDatabaseName("ix_perfis_de_formandos_foto_arquivo_id");

                    b.HasIndex("VinculoId")
                        .IsUnique()
                        .HasDatabaseName("ix_perfis_de_formandos_vinculo_id");

                    b.ToTable("perfis_de_formandos", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Formaturas.Models.Aviso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("FormaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("formatura_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("texto");

                    b.HasKey("Id")
                        .HasName("pk_avisos");

                    b.HasIndex("FormaturaId")
                        .HasDatabaseName("ix_avisos_formatura_id");

                    b.ToTable("avisos", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Formaturas.Models.Formatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<DateTime?>("AtivadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ativada_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("curso");

                    b.Property<DateTime?>("EncerradaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("encerrada_em");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("instituicao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<DateOnly?>("PrevisaoDeColacao")
                        .HasColumnType("date")
                        .HasColumnName("previsao_de_colacao");

                    b.Property<int>("QuantidadeEstimadaDeFormandos")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_estimada_de_formandos");

                    b.Property<int>("Semestre")
                        .HasColumnType("integer")
                        .HasColumnName("semestre");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_formaturas");

                    b.HasIndex("CriadoPorUsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_formaturas_rascunho_por_criador")
                        .HasFilter("status = 'Rascunho'");

                    b.ToTable("formaturas", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Formaturas.Models.VinculoDeFormatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("FormaturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("formatura_id");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("papel");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_vinculos_de_formatura");

                    b.HasIndex("FormaturaId")
                        .HasDatabaseName("ix_vinculos_de_formatura_formatura_id");

                    b.HasIndex("UsuarioId", "FormaturaId")
                        .IsUnique()
                        .HasDatabaseName("ix_vinculos_de_formatura_usuario_id_formatura_id");

                    b.ToTable("vinculos_de_formatura", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Legal.Models.ConsentimentoRegistrado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AceitoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aceito_em");

                    b.Property<Guid>("DocumentoLegalId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_legal_id");

                    b.Property<string>("EnderecoIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("endereco_ip");

                    b.Property<bool>("Revogado")
                        .HasColumnType("boolean")
                        .HasColumnName("revogado");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("versao");

                    b.HasKey("Id")
                        .HasName("pk_consentimentos");

                    b.HasIndex("DocumentoLegalId")
                        .HasDatabaseName("ix_consentimentos_documento_legal_id");

                    b.HasIndex("UsuarioId", "AceitoEm")
                        .HasDatabaseName("ix_consentimentos_usuario_id_aceito_em");

                    b.ToTable("consentimentos", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Legal.Models.DocumentoLegal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("versao");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vigente_desde");

                    b.HasKey("Id")
                        .HasName("pk_documentos_legais");

                    b.HasIndex("Tipo", "Versao")
                        .IsUnique()
                        .HasDatabaseName("ix_documentos_legais_tipo_versao");

                    b.HasIndex("Tipo", "VigenteDesde")
                        .HasDatabaseName("ix_documentos_legais_tipo_vigente_desde");

                    b.ToTable("documentos_legais", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Usuarios.Models.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_perfis");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Usuarios.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_usuarios_nome");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_perfis_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_perfis_claims_role_id");

                    b.ToTable("perfis_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_usuarios_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuarios_claims_user_id");

                    b.ToTable("usuarios_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_usuarios_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuarios_logins_user_id");

                    b.ToTable("usuarios_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_usuarios_perfis");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_usuarios_perfis_role_id");

                    b.ToTable("usuarios_perfis", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_usuarios_tokens");

                    b.ToTable("usuarios_tokens", (string)null);
                });

            modelBuilder.Entity("Backend.Business.Arquivos.Models.Arquivo", b =>
                {
                    b.HasOne("Backend.Business.Usuarios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_arquivos_asp_net_users_enviado_por_id");
                });

            modelBuilder.Entity("Backend.Business.Assinaturas.Models.Assinatura", b =>
                {
                    b.HasOne("Backend.Business.Formaturas.Models.Formatura", null)
                        .WithMany()
                        .HasForeignKey("FormaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assinaturas_formaturas_formatura_id");

                    b.HasOne("Backend.Business.Assinaturas.Models.Plano", null)
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_assinaturas_planos_plano_id");
                });

            modelBuilder.Entity("Backend.Business.Auth.Models.RefreshToken", b =>
                {
                    b.HasOne("Backend.Business.Usuarios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_asp_net_users_usuario_id");
                });

            modelBuilder.Entity("Backend.Business.Convites.Models.AceiteDeConvite", b =>
                {
                    b.HasOne("Backend.Business.Convites.Models.Convite", null)
                        .WithMany()
                        .HasForeignKey("ConviteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aceites_de_convite_convites_convite_id");

                    b.HasOne("Backend.Business.Usuarios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_aceites_de_convite_asp_net_users_usuario_id");
                });

            modelBuilder.Entity("Backend.Business.Convites.Models.Convite", b =>
                {
                    b.HasOne("Backend.Business.Usuarios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_convites_asp_net_users_criado_por_usuario_id");

                    b.HasOne("Backend.Business.Formaturas.Models.Formatura", null)
                        .WithMany()
                        .HasForeignKey("FormaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_convites_formaturas_formatura_id");
                });

            modelBuilder.Entity("Backend.Business.Formandos.Models.CorrecaoDePerfil", b =>
                {
                    b.HasOne("Backend.Business.Usuarios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AutorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_correcoes_de_perfil_asp_net_users_autor_usuario_id");

                    b.HasOne("Backend.Business.Formandos.Models.PerfilDoFormando", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_correcoes_de_perfil_perfis_de_formandos_perfil_id");
                });

            modelBuilder.Entity("Backend.Business.Formandos.Models.PerfilDoFormando", b =>
                {
                    b.HasOne("Backend.Business.Formaturas.Models.Formatura", null)
                        .WithMany()
                        .HasForeignKey("FormaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_perfis_de_formandos_formaturas_formatura_id");

                    b.HasOne("Backend.Business.Arquivos.Models.Arquivo", null)
                        .WithMany()
                        .HasForeignKey("FotoArquivoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_perfis_de_formandos_arquivos_foto_arquivo_id");

                    b.HasOne("Backend.Business.Formaturas.Models.VinculoDeFormatura", null)
                        .WithMany()
                        .HasForeignKey("VinculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_perfis_de_formandos_vinculos_vinculo_id");

                    b.OwnsOne("Backend.Business.Formandos.Models.ContatoDeEmergencia", "ContatoDeEmergencia", b1 =>
                        {
                            b1.Property<Guid>("PerfilDoFormandoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Nome")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("contato_de_emergencia_nome");

                            b1.Property<string>("Parentesco")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("contato_de_emergencia_parentesco");

                            b1.Property<string>("Telefone")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("contato_de_emergencia_telefone");

                            b1.HasKey("PerfilDoFormandoId");

                            b1.ToTable("perfis_de_formandos");

                            b1.WithOwner()
                                .HasForeignKey("PerfilDoFormandoId")
                                .HasConstraintName("fk_perfis_de_formandos_perfis_de_formandos_id");
                        });

                    b.OwnsOne("Backend.Business.Formandos.Models.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("PerfilDoFormandoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Bairro")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("endereco_bairro");

                            b1.Property<string>("Cep")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("endereco_cep");

                            b1.Property<string>("Cidade")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("endereco_cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("endereco_complemento");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("endereco_logradouro");

                            b1.Property<string>("Numero")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("endereco_numero");

                            b1.Property<string>("Uf")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("endereco_uf");

                            b1.HasKey("PerfilDoFormandoId");

                            b1.ToTable("perfis_de_formandos");

                            b1.WithOwner()
                                .HasForeignKey("PerfilDoFormandoId")
                                .HasConstraintName("fk_perfis_de_formandos_perfis_de_formandos_id");
                        });

                    b.Navigation("ContatoDeEmergencia")
                        .IsRequired();

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Business.Formaturas.Models.Aviso", b =>
                {
                    b.HasOne("Backend.Business.Formaturas.Models.Formatura", null)
                        .WithMany()
                        .HasForeignKey("FormaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avisos_formaturas_formatura_id");
                });

            modelBuilder.Entity("Backend.Business.Formaturas.Models.VinculoDeFormatura", b =>
                {
                    b.HasOne("Backend.Business.Formaturas.Models.Formatura", null)
                        .WithMany()
                        .HasForeignKey("FormaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_de_formatura_formaturas_formatura_id");

                    b.HasOne("Backend.Business.Usuarios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vinculos_de_formatura_usuarios_usuario_id");
                });

            modelBuilder.Entity("Backend.Business.Legal.Models.ConsentimentoRegistrado", b =>
                {
                    b.HasOne("Backend.Business.Legal.Models.DocumentoLegal", null)
                        .WithMany()
                        .HasForeignKey("DocumentoLegalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consentimentos_documentos_legais_documento_legal_id");

                    b.HasOne("Backend.Business.Usuarios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consentimentos_asp_net_users_usuario_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Backend.Business.Usuarios.Models.Perfil", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_perfis_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Backend.Business.Usuarios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Backend.Business.Usuarios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Backend.Business.Usuarios.Models.Perfil", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_perfis_perfis_role_id");

                    b.HasOne("Backend.Business.Usuarios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_perfis_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Backend.Business.Usuarios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_tokens_usuarios_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
